/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package org.opensearch.index.store.cipher;

import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.Provider;
import java.util.Arrays;

import javax.crypto.Cipher;
import javax.crypto.NoSuchPaddingException;

import org.opensearch.index.store.CryptoDirectoryFactory;
import org.opensearch.index.store.footer.EncryptionMetadataTrailer;
import org.opensearch.index.store.key.HkdfKeyDerivation;

/**
 * Factory utility for creating and initializing Cipher instances
 *
 * This class is tailored for symmetric encryption modes like AES-CTR,
 * where a block counter is appended to the IV.
 *
 * @opensearch.internal
 */
public class AesCipherFactory {

    /**
     * Private constructor to prevent instantiation of utility class.
     */
    private AesCipherFactory() {}

    /** AES block size in terms of 2 power bytes (16 bytes). Required for counter calculations. */
    public static final int AES_BLOCK_SIZE_BYTES_IN_POWER = 4;

    /** Number of bytes used for the counter in the IV (last 4 bytes). */
    public static final int COUNTER_SIZE_BYTES = 4;

    /** Total IV array length (typically 16 bytes for AES). */
    public static final int IV_ARRAY_LENGTH = 16;

    /** The algorrithm. */
    public static final String ALGORITHM = "AES";

    /**
     * Returns a new Cipher instance configured for AES/CTR/NoPadding using the given provider.
     *
     * @param provider The JCE provider to use (e.g., SunJCE, BouncyCastle)
     * @return A configured {@link Cipher} instance
     * @throws RuntimeException If the algorithm or padding is not supported
     */
    public static Cipher getCipher(Provider provider) {
        try {
            return Cipher.getInstance("AES/CTR/NoPadding", provider);
        } catch (NoSuchPaddingException | NoSuchAlgorithmException e) {
            throw new RuntimeException("Failed to get cipher instance", e);
        }
    }

    /**
     * Thread-local cipher pool for AES/CTR/NoPadding operations.
     * Each thread gets its own cipher instance to avoid synchronization overhead.
     */
    public static final ThreadLocal<Cipher> CIPHER_POOL = ThreadLocal.withInitial(() -> {
        try {
            // todo we can make provider comfigirable but for now with AES/CTR, SunJCE works best
            // in terms of performance.
            return Cipher.getInstance("AES/CTR/NoPadding", CryptoDirectoryFactory.DEFAULT_CRYPTO_PROVIDER);
        } catch (NoSuchAlgorithmException | NoSuchProviderException | NoSuchPaddingException e) {
            throw new RuntimeException(e);
        }
    });

    /**
     * Computes an offset-adjusted IV for CTR mode decryption at a specific file position.
     * This allows seeking into an encrypted stream without re-processing prior blocks.
     *
     * <p>The method calculates which AES block corresponds to the given byte offset and updates
     * the last 4 bytes of the IV with a block counter value. The counter is incremented by 2
     * to maintain compatibility with GCM mode counter semantics, where:
     * <ul>
     * <li>Counter 0: Reserved for GCM internal use</li>
     * <li>Counter 1: Used for authentication data processing</li>
     * <li>Counter 2+: Used for actual data block encryption</li>
     * </ul>
     *
     * <p>This ensures that CTR mode IVs generated by this method can be safely used in mixed
     * environments where both CTR and GCM modes might be employed, preventing counter collision
     * and maintaining cryptographic security.
     *
     * @param baseIV the base initialization vector (typically 16 bytes)
     * @param offset the byte offset in the file/stream to compute the IV for
     * @return a new IV with the counter field adjusted for the specified offset
     * @throws IllegalArgumentException if baseIV is null or has invalid length
     */
    public static byte[] computeOffsetIVForAesGcmEncrypted(byte[] baseIV, long offset) {
        byte[] ivCopy = Arrays.copyOf(baseIV, baseIV.length);
        int blockOffset = (int) (offset >> AES_BLOCK_SIZE_BYTES_IN_POWER);

        // Add 2 for GCM compatibility: counter 0 (reserved) + counter 1 (auth) + data counters start at 2
        blockOffset += 2;

        // Set the 4-byte counter in big-endian format (last 4 bytes of IV)
        ivCopy[AesCipherFactory.IV_ARRAY_LENGTH - 1] = (byte) blockOffset;
        ivCopy[AesCipherFactory.IV_ARRAY_LENGTH - 2] = (byte) (blockOffset >>> 8);
        ivCopy[AesCipherFactory.IV_ARRAY_LENGTH - 3] = (byte) (blockOffset >>> 16);
        ivCopy[AesCipherFactory.IV_ARRAY_LENGTH - 4] = (byte) (blockOffset >>> 24);

        return ivCopy;
    }

    /**
     * Computes a per-chunk GCM IV for AES-GCM translog chunks.
     *
     * <p>Unlike {@link #computeOffsetIVForAesGcmEncrypted}, which adjusts the trailing four bytes
     * (the CTR-mode counter block, ignored by GCM since GCM derives its 96-bit nonce from the
     * <em>first</em> 12 bytes of the IV), this method varies the bytes that actually form the GCM
     * nonce so that each chunk in a file gets a distinct IV. AES-GCM requires a distinct IV per
     * message under a given key (NIST SP 800-38D); deriving the chunk IV in the trailing bytes left
     * every chunk in a file with the same effective GCM IV.
     *
     * <p>The 96-bit nonce follows the deterministic construction in NIST SP 800-38D &sect;8.2.1:
     * <ul>
     *   <li>bytes 0&ndash;7: per-file fixed field, taken from {@code baseIV[0..7]} (derived per
     *       translog UUID via HKDF, so it differs across files);</li>
     *   <li>bytes 8&ndash;11: invocation field, a big-endian 32-bit chunk index (unique within a file).</li>
     * </ul>
     *
     * <p>A 16-byte array is returned for layout compatibility with the GCM helpers (which read the
     * leading 12 bytes only); bytes 12&ndash;15 are unused by GCM (they are where the CTR helper
     * {@link #computeOffsetIVForAesGcmEncrypted} would place its counter, and are left as a copy of
     * {@code baseIV} here). The 32-bit chunk index bounds a file to 2<sup>32</sup> chunks
     * (~32&nbsp;PB at 8&nbsp;KB chunks), far above the translog roll size.
     *
     * @param baseIV the per-file base IV (at least 12 bytes; bytes 0&ndash;7 used as the fixed field)
     * @param chunkIndex the zero-based chunk index within the file (0 &le; index &le; 2<sup>32</sup>-1)
     * @return a 16-byte array whose first 12 bytes are the GCM nonce for this chunk
     * @throws IllegalArgumentException if baseIV is null/too short or chunkIndex is out of range
     */
    public static byte[] computeChunkIVForAesGcm(byte[] baseIV, long chunkIndex) {
        if (baseIV == null || baseIV.length < 12) {
            throw new IllegalArgumentException("baseIV must be at least 12 bytes");
        }
        if (chunkIndex < 0 || chunkIndex > 0xFFFFFFFFL) {
            throw new IllegalArgumentException("chunkIndex out of 32-bit range: " + chunkIndex);
        }
        byte[] iv = Arrays.copyOf(baseIV, IV_ARRAY_LENGTH);
        // bytes 0..7 retain baseIV (per-file fixed field); bytes 8..11 = big-endian chunk index
        iv[8] = (byte) (chunkIndex >>> 24);
        iv[9] = (byte) (chunkIndex >>> 16);
        iv[10] = (byte) (chunkIndex >>> 8);
        iv[11] = (byte) chunkIndex;
        return iv;
    }

    /**
     * Computes an offset-adjusted IV for pure CTR mode encryption/decryption at a specific file position.
     * This method generates IVs for data that was originally encrypted using standard CTR mode without
     * GCM compatibility adjustments.
     *
     * <p>The method calculates which AES block corresponds to the given byte offset and updates
     * the last 4 bytes of the IV with the exact block counter value (starting from 0). This is used
     * for decrypting data that was encrypted with standard CTR mode where counters begin at 0.
     *
     * @param baseIV the base initialization vector (typically 16 bytes)
     * @param offset the byte offset in the file/stream to compute the IV for
     * @return a new IV with the counter field adjusted for the specified offset (starting from counter 0)
     * @throws IllegalArgumentException if baseIV is null or has invalid length
     */
    public static byte[] computeOffsetIVForAesCtrEncrypted(byte[] baseIV, long offset) {
        byte[] ivCopy = Arrays.copyOf(baseIV, baseIV.length);
        int blockOffset = (int) (offset >> AES_BLOCK_SIZE_BYTES_IN_POWER);

        // Set the 4-byte counter in big-endian format (last 4 bytes of IV)
        ivCopy[AesCipherFactory.IV_ARRAY_LENGTH - 1] = (byte) blockOffset;
        ivCopy[AesCipherFactory.IV_ARRAY_LENGTH - 2] = (byte) (blockOffset >>> 8);
        ivCopy[AesCipherFactory.IV_ARRAY_LENGTH - 3] = (byte) (blockOffset >>> 16);
        ivCopy[AesCipherFactory.IV_ARRAY_LENGTH - 4] = (byte) (blockOffset >>> 24);

        return ivCopy;
    }

    /**
     * Compute frame-specific IV for large file encryption
     *
     * @param directoryKey      the directory's master key (32 bytes)
     * @param messageId         the file's unique MessageId (16 bytes)
     * @param frameNumber       the frame number (0-based)
     * @param offsetWithinFrame the byte offset within the frame
     * @param normalizedFilePath the normalized file path string
     * @param encryptionMetadataCache the encryption metadata cache
     * @return frame-specific IV for encryption/decryption
     */
    public static byte[] computeFrameIV(
        byte[] directoryKey,
        byte[] messageId,
        long frameNumber,
        long offsetWithinFrame,
        String normalizedFilePath,
        EncryptionMetadataCache encryptionMetadataCache
    ) {
        if (messageId.length != 16) {
            throw new IllegalArgumentException("MessageId must be 16 bytes");
        }
        if (frameNumber < 0 || frameNumber >= EncryptionMetadataTrailer.MAX_FRAMES_PER_FILE) {
            throw new IllegalArgumentException("Invalid frame number: " + frameNumber);
        }

        // Get or derive frame base IV from cache
        byte[] frameBaseIV = encryptionMetadataCache.getFrameIv(normalizedFilePath, frameNumber);
        if (frameBaseIV == null) {
            String frameContext = EncryptionMetadataTrailer.FRAME_CONTEXT_PREFIX + frameNumber;
            frameBaseIV = HkdfKeyDerivation.deriveKey(directoryKey, messageId, frameContext, 16);
            encryptionMetadataCache.putFrameIv(normalizedFilePath, frameNumber, frameBaseIV);
        }

        // Modify last 4 bytes for block counter within frame
        byte[] frameIV = new byte[16];
        System.arraycopy(frameBaseIV, 0, frameIV, 0, 16);
        int blockOffset = (int) (offsetWithinFrame >> AES_BLOCK_SIZE_BYTES_IN_POWER);

        // Add 2 for GCM compatibility: counter 0 (reserved) + counter 1 (auth) + data counters start at 2
        blockOffset += 2;

        // Bytes 12-15: Block counter within frame (4 bytes, big-endian)
        frameIV[12] = (byte) (blockOffset >>> 24);
        frameIV[13] = (byte) (blockOffset >>> 16);
        frameIV[14] = (byte) (blockOffset >>> 8);
        frameIV[15] = (byte) blockOffset;

        return frameIV;
    }
}
